'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
Namespace My


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
	Friend Class Resources

		Private Shared resourceMan As Global.System.Resources.ResourceManager

		Private Shared resourceCulture As Global.System.Globalization.CultureInfo

		<Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
		Friend Sub New()
		End Sub

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Example of a Custom Task: Sets the substrings on a label and then prints it..
		''' </summary>
		Friend Shared ReadOnly Property CustomTaskDescription() As String
			Get
				Return ResourceManager.GetString("CustomTaskDescription", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to CustomTask.
		''' </summary>
		Friend Shared ReadOnly Property CustomTaskLabel() As String
			Get
				Return ResourceManager.GetString("CustomTaskLabel", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Task that exports a print preview image of a format as if it was printed to the default printer..
		''' </summary>
		Friend Shared ReadOnly Property ExportPreviewDescription() As String
			Get
				Return ResourceManager.GetString("ExportPreviewDescription", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Export Print Preview Task.
		''' </summary>
		Friend Shared ReadOnly Property ExportPreviewLabel() As String
			Get
				Return ResourceManager.GetString("ExportPreviewLabel", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Task that exports a thumbnail image of a format..
		''' </summary>
		Friend Shared ReadOnly Property ExportThumbnailDescription() As String
			Get
				Return ResourceManager.GetString("ExportThumbnailDescription", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Export Thumbnail Task.
		''' </summary>
		Friend Shared ReadOnly Property ExportThumbnailLabel() As String
			Get
				Return ResourceManager.GetString("ExportThumbnailLabel", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Task that gets the format&apos;s named substrings..
		''' </summary>
		Friend Shared ReadOnly Property GetFormatTaskDescription() As String
			Get
				Return ResourceManager.GetString("GetFormatTaskDescription", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Get Format Task.
		''' </summary>
		Friend Shared ReadOnly Property GetFormatTaskLabel() As String
			Get
				Return ResourceManager.GetString("GetFormatTaskLabel", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Task that runs three Print Tasks as a group (All on the same Engine)..
		''' </summary>
		Friend Shared ReadOnly Property GroupTaskDescription() As String
			Get
				Return ResourceManager.GetString("GroupTaskDescription", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Group Task.
		''' </summary>
		Friend Shared ReadOnly Property GroupTaskLabel() As String
			Get
				Return ResourceManager.GetString("GroupTaskLabel", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to No Task Selected..
		''' </summary>
		Friend Shared ReadOnly Property NoTaskDescription() As String
			Get
				Return ResourceManager.GetString("NoTaskDescription", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Task that prints a format to the default printer..
		''' </summary>
		Friend Shared ReadOnly Property PrintTaskDescription() As String
			Get
				Return ResourceManager.GetString("PrintTaskDescription", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Print Task.
		''' </summary>
		Friend Shared ReadOnly Property PrintTaskLabel() As String
			Get
				Return ResourceManager.GetString("PrintTaskLabel", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Task that executes an XMLScript..
		''' </summary>
		Friend Shared ReadOnly Property XMLScriptTaskDescription() As String
			Get
				Return ResourceManager.GetString("XMLScriptTaskDescription", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to XMLScript Task.
		''' </summary>
		Friend Shared ReadOnly Property XMLScriptTaskLabel() As String
			Get
				Return ResourceManager.GetString("XMLScriptTaskLabel", resourceCulture)
			End Get
		End Property
	End Class
End Namespace
