//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMaster.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskMaster.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example of a Custom Task: Sets the substrings on a label and then prints it..
        /// </summary>
        internal static string CustomTaskDescription {
            get {
                return ResourceManager.GetString("CustomTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomTask.
        /// </summary>
        internal static string CustomTaskLabel {
            get {
                return ResourceManager.GetString("CustomTaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task that exports a print preview image of a format as if it was printed to the default printer..
        /// </summary>
        internal static string ExportPreviewDescription {
            get {
                return ResourceManager.GetString("ExportPreviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Print Preview Task.
        /// </summary>
        internal static string ExportPreviewLabel {
            get {
                return ResourceManager.GetString("ExportPreviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task that exports a thumbnail image of a format..
        /// </summary>
        internal static string ExportThumbnailDescription {
            get {
                return ResourceManager.GetString("ExportThumbnailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Thumbnail Task.
        /// </summary>
        internal static string ExportThumbnailLabel {
            get {
                return ResourceManager.GetString("ExportThumbnailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task that gets the format&apos;s named substrings..
        /// </summary>
        internal static string GetFormatTaskDescription {
            get {
                return ResourceManager.GetString("GetFormatTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Format Task.
        /// </summary>
        internal static string GetFormatTaskLabel {
            get {
                return ResourceManager.GetString("GetFormatTaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task that runs three Print Tasks as a group (All on the same Engine)..
        /// </summary>
        internal static string GroupTaskDescription {
            get {
                return ResourceManager.GetString("GroupTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Task.
        /// </summary>
        internal static string GroupTaskLabel {
            get {
                return ResourceManager.GetString("GroupTaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Task Selected..
        /// </summary>
        internal static string NoTaskDescription {
            get {
                return ResourceManager.GetString("NoTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task that prints a format to the default printer..
        /// </summary>
        internal static string PrintTaskDescription {
            get {
                return ResourceManager.GetString("PrintTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Task.
        /// </summary>
        internal static string PrintTaskLabel {
            get {
                return ResourceManager.GetString("PrintTaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task that executes an XMLScript..
        /// </summary>
        internal static string XMLScriptTaskDescription {
            get {
                return ResourceManager.GetString("XMLScriptTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMLScript Task.
        /// </summary>
        internal static string XMLScriptTaskLabel {
            get {
                return ResourceManager.GetString("XMLScriptTaskLabel", resourceCulture);
            }
        }
    }
}
